### ISSUE TITLE
Use with dynamic modules

### ISSUE THREAD

**Issue by NetanelBasal** [JohnPostlethwait/stringify#26]
There is support for using like this:
```js
require('./views/' + someVar + '.tpl.html');
```
I am getting this error:
Cannot find module './views/article.tpl.html'

**Comment by JohnPostlethwait** [comment]
Try using a path that is not prefixed with the cwd. "./" maps to the current working directory, and when stringify runs it is likely not where you mean for this to be a relative path to. Try making your require path ```javascript  requir ("views/" + someVar + "tpl.html"); ``` (no prefix of "./")

**Comment by JohnPostlethwait** [comment]
Sorry for the typos - on my phone.

**Comment by NetanelBasal** [comment]
Still get this error:

Browserify Error { [Error: Cannot find module 'views/article.tpl.html'

**Comment by JohnPostlethwait** [comment]
Stringify is using [path.resolve](https://nodejs.org/docs/latest/api/path.html#path_path_resolve_from_to) to find the file, and if an error is thrown from `path.resolve`, it throws that error: https://github.com/JohnPostlethwait/stringify/blob/master/src/stringify.js#L141

Without access to the code, my only assumption is that this file is actually not there...

I'm going to try to reproduce this myself with a test – I will let you know how that goes.

**Comment by NetanelBasal** [comment]
The file is there, because when i am doing this:
require("views/article.tpl.html");
it's working.

**Comment by JohnPostlethwait** [comment]
Ok, I'll make a test with dynamic requires and see if I can reproduce it.

Thanks for the report! Sorry for the bug.

**Comment by JohnPostlethwait** [comment]
Can you try the new (4.0.0) version of Stringify? I am wondering if this was an issue with the fact that the Stringify you were using was using very old NodeJS stream APIs.

**Comment by NetanelBasal** [comment]
So i need to update node js also?

**Comment by JohnPostlethwait** [comment]
I wouldn't think so - what version are you on? 

The version I wrote this on is VERY old (0.10.26) and it just didn't work with the newer (4.0.0+) versions of Node. It was causing a lot of problems for people. If you are using a more recent version of Node, I'm curious to see if you still have this issue.

**Comment by NetanelBasal** [comment]
I'm using v0.12.2

**Comment by JohnPostlethwait** [comment]
Ok, let me install that version and see if I can reproduce.

**Comment by JohnPostlethwait** [comment]
So, after a bit of testing, and seeing this issue myself, it turns out that Browserify does not support this at all: https://github.com/substack/node-browserify/issues/377 so this will never work with Stringify either, as we are just a transformer for their require system.

**Comment by NetanelBasal** [comment]
Ok, thanks for your response

**Comment by JohnPostlethwait** [comment]
Sure thing! Sorry it won't work out... If you REALLY need dynamic requires, you could probably first run it through something that is capable of resolving those dynamic module requirements, and outputting a new file, that you can then Browserify...  (I don't know offhand of such a tool, but there may be one.)

Sorry for the bad news, and sorry it took me so long to look at.

**Comment by NetanelBasal** [comment]
I will change my build tool to be webpack

**Comment by JohnPostlethwait** [comment]
It looks like https://www.npmjs.com/package/bulkify may be what you want if you want to continue using Browserify. I haven't tried it though...

**Comment by NetanelBasal** [comment]
Thank's i will take a look :+1:

**Comment by JohnPostlethwait** [comment]
Good luck! :smile:
